---
- hosts: local
  vars:
   - docroot: /var/www/myservers.com/public
  tasks:
   - name: Add Nginx Repository
     apt_repository: repo='ppa:nginx/stable' state=present
     register: ppastable

   - name: Install Nginx
     apt: pkg=nginx state=installed update_cache=true
     when: ppastable|success
     register: nginxinstalled
     notify:
      - Start Nginx

   - name: Create Web Root
     when: nginxinstalled|success
     file: dest={{ '{{' }} docroot {{ '}}' }} mode=775 state=directory owner=www-data group=www-data
     notify:
      - Reload Nginx

  handlers:
   - name: Start Nginx
     service: name=nginx state=started

    - name: Reload Nginx
      service: name=nginx state=reloaded
      
# new here are the register and when directives. These tell Ansible to run a Task when something else happens.
# The docroot variable is defined in the var section. It's then used as the destination argument of the file module which creates the defined directory.

# Add Nginx Repository - Add the Nginx stable PPA to get the latest stable version of Nginx, using the apt_repository module.
# Install Nginx - Installs Nginx using the Apt module.
# Create Web Root - Finally, create a web root directory.

